services:

  ethereum-get:
    image: ethereum-geth
    container_name: ethereum-geth
    environment:
    # - PUID=1000
    # - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "7396:7396"
      - "36330:36330" #optional
    volumes:
      - ./config:/config
    healthcheck:
      test: curl http://localhost:7396 || exit 1
    restart: unless-stopped

  httpd:
    image: httpd:alpine
    container_name: httpd
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/
    healthcheck:
      test: wget --server-response --spider --quiet  http://localhost || exit 1

  # https://app.zerossl.com/certificate/new
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - ethereum-geth
      - node-red
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # - ./key.pem:/root/ssl/key.pem              # self-signed (openssl)
    # - ./cert.pem:/root/ssl/cert.pem            # self-signed (openssl)
    # - ./private.key:/etc/ssl/private.key         # CA-signed (ZeroSSL)
    # - ./certificate.crt:/etc/ssl/certificate.crt # CA-signed (ZeroSSL)
    healthcheck:
      test: service nginx status || exit 1

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    # - node-red-data:/data


# volumes:
#   node-red-data:
